### ISSUE TITLE
How to do the test in colab 

### ISSUE THREAD

**Issue by Ammar-Ahmad-Khan** [geyuying/PF-AFN#13]
I tried running the code in Colab, but the results weren't the same as yours. I think it is because of the environment issue. How can I create the same environment in Colab

**Comment by Ammar-Ahmad-Khan** [comment]
It worked in Colab

**Comment by amrahsmaytas** [comment]
Hi @Ammar-Ahmad-Khan 
Can you please the working colab?
Thanks.

**Comment by RonenRoz** [comment]
Hi @Ammar-Ahmad-Khan
Can I get it also?
Forever in your debt

**Comment by adakoda** [comment]
Here is a notebook. Please see this PR https://github.com/geyuying/PF-AFN/pull/44.
