### ISSUE TITLE
problem with training

### ISSUE THREAD

**Issue by amandazw** [geyuying/PF-AFN#15]
Hi! Thanks for your efforts. 
Now I want to train the model with my own dataset, and I have 2 questions. First, is if the custom image with different size (like 800*800) ,do i need to change the network architecture? and how? Another one is the train label number is 14,but the number of  CIHP_PGN label is 20.How can I solve it. thanks

**Comment by spencerxhani** [comment]
Hi @amandazw, 
did you train on your own dataset successfully?  I have these same questions. 
Thank you!

**Comment by amandazw** [comment]
@spencerxhani sorry,I failed.
