### ISSUE TITLE
test result

### ISSUE THREAD

**Issue by amandazw** [geyuying/PF-AFN#20]
![1](https://user-images.githubusercontent.com/20120287/113993631-3e68e200-9887-11eb-8882-3340b04d2dec.jpg)

![3](https://user-images.githubusercontent.com/20120287/113993837-6eb08080-9887-11eb-8dc6-523452960ba3.jpg)

When I use my own image test，the results like this，any suggestion? thx

**Comment by SahilDhull** [comment]
Hi, I am trying to train and test this model.
And so for general knowledge, wanted to know what were you doing wrong that resulted in this? Or what did you do finally to make it correct?

**Comment by cloudy4next** [comment]
@SahilDhull  which model?
Specify Please!!!

**Comment by amandazw** [comment]
@SahilDhull Hi, I finally made it correct

**Comment by Denrose11** [comment]
> @SahilDhull Hi, I finally made it correct

can you please tell me how to segregate the test results into three individual images like a person, dress, and the resultant image into individual images

**Comment by kayabutterkun** [comment]
@amandazw Hi I'm facing similar problem. Do you have any tips to solve it? Thank you in advance

**Comment by kayabutterkun** [comment]
Ah ok I figured it out. Checkpoints should be saved in PF_AFN/PF_AFN_test/checkpoints
