### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by dhananjay1710** [geyuying/PF-AFN#27]
Thank you so much for implementing this research paper in such a convenient format for us! I just needed a little help!
I have a custom dataset with a directory for "clothes", "clothes-masks", "test-images", how do I go about testing it?
My approach, from what I understood in the code, was to add the images in the folders and then edit the demo.txt to form pairs accordingly? Is there an easier/more automated method for doing this? Thank you for your help!

**Comment by SahilDhull** [comment]
You can write a script that picks up random image from the folders and writes them in demo.txt

**Comment by dhananjay1710** [comment]
> You can write a script that picks up random image from the folders and writes them in demo.txt

Right, that is what i proceeded to do, thank you !
