### ISSUE TITLE
TypeError: 'int' object is not iterable

### ISSUE THREAD

**Issue by Zibin-Z** [geyuying/PF-AFN#29]
hi~
I'm using a single GPU to train the train_PBAFN_stage1.py, but I have this problem：TypeError: 'int' object is not iterable.
What is the reason for this problem? 
![image](https://user-images.githubusercontent.com/49144373/117261214-7b25fa00-ae82-11eb-9fbf-ba4a7c605e39.png)

**Comment by geyuying** [comment]
Our training code uses distributed data parallel (nn.DistributedDataParallel) in pytorch. If you want to train the model with one GPU, you need to remove DistributedDataParallel and move the model to GPU only by calling model.cuda(). You also need change the way to load data and you can refer to https://github.com/switchablenorms/DeepFashion_Try_On/blob/master/ACGPN_train/train.py
