### ISSUE TITLE
[Thank you] Cannot quite replicate the results.

### ISSUE THREAD

**Issue by PLXIV** [geyuying/PF-AFN#3]
First of all, thank you very much for your contribution. This work seems to work considerably better than ACGPN and other approaches tackling this task.

I wanted to issue that even if I followed the steps to run it, the results I got from running the test.sh are quite different from the ones you showcase. Here is an example:

![Captura](https://user-images.githubusercontent.com/20990263/110517710-7c99a700-810b-11eb-8a89-c7034baa1213.JPG)

Has anyone encountered similar misaligments? Do you believe that those are caused by mismatching of the dependency versions? I am aware that you comment about it in the markdown, but I would like to ask how slight differences impacts in the library versions affects in the final output.

Thank you very much for your time and congratulations for your publication.

Edit: typo

**Comment by geyuying** [comment]
Thanks for your interest.

What is your version of cupy? We encountered the similar misalignments when the version of cupy is not 6.0.0. After changing the verison of cupy, the misalignments disappear. That's why we emphasize on the version of cupy in the markdown.

**Comment by PLXIV** [comment]
Thank you for your reply.

My version of cupy is 6.0.0 seems to be the proper one, here's the pip list of my installation:

Package           Version
----------------- -------------------
certifi           2020.12.5
cffi              1.14.5
cupy              6.0.0
dataclasses       0.8
fastrlock         0.5
mkl-fft           1.3.0
mkl-random        1.1.1
mkl-service       2.3.0
numpy             1.19.2
olefile           0.46
opencv-python     4.5.1.48
Pillow            8.1.2
pip               21.0.1
pycparser         2.20
setuptools        52.0.0.post20210125
six               1.15.0
torch             1.7.1+cu110
torchaudio        0.7.2
torchvision       0.8.2+cu110
typing-extensions 3.7.4.3
wheel             0.36.2


My main changes are the usage of pytorch 1.7.1 with cuda 11 since my gpus (RTX3090) does not work well with cuda 9.0 and pytorch 1.1.0 (it wasn't running at all).

I will try to replicate these results in another computer with cuda 9.0 and see if it works well in that one. If anyone has encountered similar problems please make us know.

**Comment by LeoXing1996** [comment]
> Thank you for your reply.
> 
> My version of cupy is 6.0.0 seems to be the proper one, here's the pip list of my installation:
> 
> Package Version
> 
> certifi 2020.12.5
> cffi 1.14.5
> cupy 6.0.0
> dataclasses 0.8
> fastrlock 0.5
> mkl-fft 1.3.0
> mkl-random 1.1.1
> mkl-service 2.3.0
> numpy 1.19.2
> olefile 0.46
> opencv-python 4.5.1.48
> Pillow 8.1.2
> pip 21.0.1
> pycparser 2.20
> setuptools 52.0.0.post20210125
> six 1.15.0
> torch 1.7.1+cu110
> torchaudio 0.7.2
> torchvision 0.8.2+cu110
> typing-extensions 3.7.4.3
> wheel 0.36.2
> 
> My main changes are the usage of pytorch 1.7.1 with cuda 11 since my gpus (RTX3090) does not work well with cuda 9.0 and pytorch 1.1.0 (it wasn't running at all).
> 
> I will try to replicate these results in another computer with cuda 9.0 and see if it works well in that one. If anyone has encountered similar problems please make us know.
 
Setting `align_corners=True` in `F.grid_sample` makes the code output correct results.
I use 3090 and pytorch 1.7.1+cu110 as well.

**Comment by PLXIV** [comment]
Thank you LeoXing1996, I can confirm that is works properly with the changed mentioned.

All the best,

**Comment by lyx0208** [comment]
@LeoXing1996 @PLXIV I failed to install cupy6.0.0 with 3090 and pytorch 1.7.1, is there any changes I should make to install this package?

**Comment by PLXIV** [comment]
@lyx0208 My installation was very smooth within my docker container. You can see the dependencies I installed in this post. I used Python 3.6.13, hope if helps.

**Comment by gexahedron** [comment]
> @LeoXing1996 @PLXIV I failed to install cupy6.0.0 with 3090 and pytorch 1.7.1, is there any changes I should make to install this package?

I think cupy 8.5 is also fine (at least I got the same results as in provided demo images).

**Comment by arunsubk** [comment]
> 

Dear @PLXIV , With reference to your comment https://github.com/geyuying/PF-AFN/issues/3#issuecomment-802692962  Could you please help me with the dockerfile if possible? I am asking this because I am assuming you are not using conda inside docker; in absence I am finding installing cupy=6.0.0 impossible with higher versions of cuda (it forces me to look at cupy-cuda10.1 etc, which I see is generating bad outputs. Might help to have a dockerfile if possible.
Thank you

**Comment by LeoMyMe** [comment]
> > Thank you for your reply.
> > My version of cupy is 6.0.0 seems to be the proper one, here's the pip list of my installation:
> > Package Version
> > certifi 2020.12.5
> > cffi 1.14.5
> > cupy 6.0.0
> > dataclasses 0.8
> > fastrlock 0.5
> > mkl-fft 1.3.0
> > mkl-random 1.1.1
> > mkl-service 2.3.0
> > numpy 1.19.2
> > olefile 0.46
> > opencv-python 4.5.1.48
> > Pillow 8.1.2
> > pip 21.0.1
> > pycparser 2.20
> > setuptools 52.0.0.post20210125
> > six 1.15.0
> > torch 1.7.1+cu110
> > torchaudio 0.7.2
> > torchvision 0.8.2+cu110
> > typing-extensions 3.7.4.3
> > wheel 0.36.2
> > My main changes are the usage of pytorch 1.7.1 with cuda 11 since my gpus (RTX3090) does not work well with cuda 9.0 and pytorch 1.1.0 (it wasn't running at all).
> > I will try to replicate these results in another computer with cuda 9.0 and see if it works well in that one. If anyone has encountered similar problems please make us know.
> 
> Setting `align_corners=True` in `F.grid_sample` makes the code output correct results. I use 3090 and pytorch 1.7.1+cu110 as well.

Hello,Did you hava a problem:
Given input size: (512x2x1). Calculated output size: (512x1x0). Output size is too small
when you were training?
