### ISSUE TITLE
About running training code on a GPU

### ISSUE THREAD

**Issue by Zibin-Z** [geyuying/PF-AFN#32]
I only have one GPU, and now I have successfully run test.py.
But when I try to run train***.py, it will report this error:
![image](https://user-images.githubusercontent.com/49144373/117400683-be8d7080-af35-11eb-8dbb-7d4fe8025323.png)
So I added some parameters by searching for information, and then running, it will report this error. 
![image](https://user-images.githubusercontent.com/49144373/117400802-f5fc1d00-af35-11eb-8400-1de0ff1adbc0.png)

I don’t know how to solve this error so far.How can I solve this problem?

**Comment by geyuying** [comment]
Our training code uses distributed data parallel (nn.DistributedDataParallel) in pytorch. If you want to train the model with one GPU, you need to remove DistributedDataParallel and move the model to GPU only by calling model.cuda(). You also need change the way to load data and you can refer to https://github.com/switchablenorms/DeepFashion_Try_On/blob/master/ACGPN_train/train.py

**Comment by Zibin-Z** [comment]
> Our training code uses distributed data parallel (nn.DistributedDataParallel) in pytorch. If you want to train the model with one GPU, you need to remove DistributedDataParallel and move the model to GPU only by calling model.cuda(). You also need change the way to load data and you can refer to https://github.com/switchablenorms/DeepFashion_Try_On/blob/master/ACGPN_train/train.py

I modified the way of loading data and removed the corresponding places according to your guidance, as shown in the following figure:

**Comment by Zibin-Z** [comment]
> Our training code uses distributed data parallel (nn.DistributedDataParallel) in pytorch. If you want to train the model with one GPU, you need to remove DistributedDataParallel and move the model to GPU only by calling model.cuda(). You also need change the way to load data and you can refer to https://github.com/switchablenorms/DeepFashion_Try_On/blob/master/ACGPN_train/train.py

I modified the way of loading data and removed the corresponding places according to your guidance, as shown in the following figure:
![image](https://user-images.githubusercontent.com/49144373/117412349-48920500-af47-11eb-8421-ff9dc1104487.png)
![image](https://user-images.githubusercontent.com/49144373/117412371-4f207c80-af47-11eb-9bb9-88d96f6b5af6.png)
But it didn't solve the problem.   **TypeError: 'int' object is not iterable**
Through debugging, I saw that this problem occurred at this position in the picture below.
![image](https://user-images.githubusercontent.com/49144373/117412685-a292ca80-af47-11eb-966f-6c460df88aa9.png)
This should be of type **img**, but here it appears **ndarrary**.The error is reported here, do you know the reason?
