### ISSUE TITLE
Test using CPU

### ISSUE THREAD

**Issue by bondbenz** [geyuying/PF-AFN#39]
Hello , i want to test the pretrained model using only CPU but asking always for cuda even that I disabled cuda device.

**Comment by cloudy4next** [comment]
@bondbenz, If i'm not wrong, you can't test on cpu cause the  matrix is used to calucate it's not numpy , so it's require cupy and cupy needs gpu to performe calculation 👍🏾

**Comment by bondbenz** [comment]
Oh shoot thats bad , i tried to replace cuda and cupy and load model using cpu but still nothing keep getting cuda device unavailable.

**Comment by cloudy4next** [comment]
@bondbenz cupy is intregated with cuda itself for some corelation loss or something . try with a gpu ✌🏾

**Comment by bondbenz** [comment]
Thank you for your replies
