### ISSUE TITLE
VITON-HD

### ISSUE THREAD

**Issue by artemkurylev** [geyuying/PF-AFN#4]
Hi, first of all, great work!
Second, can you please provide supplementary materials as well as access to VITON-HD dataset

**Comment by geyuying** [comment]
The supplementary materials will be published in CVPR camera-readly version. If you need VITON-HD dataset, please contact the authors of  VITON (https://github.com/xthan/VITON). Thanks!

**Comment by geyuying** [comment]
Hi, the supplementary material has been uploaded to https://github.com/geyuying/PF-AFN/blob/main/PFAFN_supp.pdf

**Comment by artemkurylev** [comment]
Thanks!

**Comment by jokerlc** [comment]
@artemkurylev hi, did you get the VITON_HD dataset yet?

**Comment by artemkurylev** [comment]
Unfortunately authors of VITON does not know anything about VITON-HD 😞

**Comment by jokerlc** [comment]
all right,  thanks anyway
















在 2021-05-06 18:23:52，"Artem Kurylev" ***@***.***> 写道：

Unfortunately authors of VITON does not know anything about VITON-HD

**Comment by ajay01994** [comment]
There is nothing called as  VITON HD but rather its VITON HQ - https://github.com/ChongjianGE/DCTON
