### ISSUE TITLE
train_PBAFN_stage1 failed

### ISSUE THREAD

**Issue by crinai** [geyuying/PF-AFN#40]
I use this wonderful project with another CV project,whitch  require the core ENV bellow:
torch                     1.8.0+cu111         
torchaudio                0.8.0    
torchvision               0.9.0+cu111 
cuda                      0.0.1            
cudatoolkit               11.1.1            
cupy-cuda111              8.6.0
cupy                      9.0.0  
cupy-cuda111              8.6.0 
The script [scripts/train_PBAFN_stage1.sh] return this error " RuntimeError: Given input size: (512x2x1). Calculated output size: (512x1x0). Output size is too small", can anyone help me,thank you!

**Comment by crinai** [comment]
> you need to downgrade pytorch to 1.1.o else go to 2dmaxpool of 1.8 and modify
than you, the new GPUs doesn't support CUDA9.2，so I can't downgrade the torch version to 1.1.0， I will try modify the pool later。

**Comment by Lipurple** [comment]
hello, I meet the same question and I wonder if you have solved this problem
