### ISSUE TITLE
Question about FID evaluatioin on VITON test_pairs.txt

### ISSUE THREAD

**Issue by HoYinTam** [geyuying/PF-AFN#48]
Hi! That is a brilliant work! 

I wonder the detail rule on FID evalutaion since there cannot find the GT img of the tryon output from test_pairs.txt. Therefore, it is confused to me that calculation of FID between the output and the dataset. Should I use test_pairs_same.txt (https://github.com/minar09/cp-vton-plus/blob/master/data/test_pairs_same.txt ) ?

**Comment by geyuying** [comment]
Yes, you need to use the same test_pairs_same.txt.
