### ISSUE TITLE
Image extracting problem with Training

### ISSUE THREAD

**Issue by Rerorerororo** [geyuying/PF-AFN#68]
Thank you for the amazing work!

I am currently training **PB-AFN stage 1** on Google Golab,
and I have trouble with displaying "person_clothes" on the 2nd column.
I am certain that I have upload the train_label folder on google drive and the root is correct, and I have check the code but cannot find where the problem is.

Could anyone help me with this issue?

![Snipaste_2022-06-05_14-52-08](https://user-images.githubusercontent.com/32993457/172039176-a0a4c66e-70ed-4bd6-854e-a8720844b28a.png)

**Comment by Rerorerororo** [comment]
I figure out that the labels are all negative values, which cannot satisfy the following statement:
torch.FloatTensor((data['label'].cpu().numpy()==8)

Is there a way to convert the values?
![image](https://user-images.githubusercontent.com/32993457/172049803-836a5887-6261-4dba-bb60-5cff9e892528.png)

**Comment by Rerorerororo** [comment]
So for unkown reason the dictionary for labels is different, here's the list if anyone needed.
![image](https://user-images.githubusercontent.com/32993457/172093869-104d4fbf-e96a-420f-a43c-d9825c2c03d2.png)

**Comment by wang674** [comment]
Hello, I also encountered your situation during training. Have you solved it

**Comment by wang674** [comment]
![image](https://user-images.githubusercontent.com/81903513/193197022-b4b5dff8-b389-4181-982f-2fccb683842c.png)

**Comment by hyyuan123** [comment]
@wang674, I also encountered your situation during training. Have you solved it

> 
, I also encountered your situation during training. Have you solved it
