### ISSUE TITLE
Train image warping issues

### ISSUE THREAD

**Issue by wang674** [geyuying/PF-AFN#75]
When I was training, I found that most of the pictures were not properly extracted, some could and some could not, and most of them could not be extracted correctly
![image](https://user-images.githubusercontent.com/81903513/193197445-00122af4-f74f-4941-a20a-1436390fd11a.png)
![image](https://user-images.githubusercontent.com/81903513/193197745-a8332abc-b9ab-4b16-ad66-dbe0458b83da.png)
Can you help me?

**Comment by wang674** [comment]
@geyuying

**Comment by ddghgf** [comment]
> When I was training, I found that most of the pictures were not properly extracted, some could and some could not, and most of them could not be extracted correctly ![image](https://user-images.githubusercontent.com/81903513/193197445-00122af4-f74f-4941-a20a-1436390fd11a.png) ![image](https://user-images.githubusercontent.com/81903513/193197745-a8332abc-b9ab-4b16-ad66-dbe0458b83da.png) Can you help me?

hello,I am a beginner in ml,so I fell sorry that i can not help you.i just want to know the detailed routine on installing and seting of the environment.can you help me?God bless you!

**Comment by wang674** [comment]
python 3.6
torch 1.1




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "geyuying/PF-AFN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月15日(星期六) 晚上7:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [geyuying/PF-AFN] Train image warping issues (Issue #75)





  
When I was training, I found that most of the pictures were not properly extracted, some could and some could not, and most of them could not be extracted correctly   Can you help me?
  
hello,I am a beginner in ml,so I fell sorry that i can not help you.i just want to know the detailed routine on installing and seting of the environment.can you help me?God bless you!

**Comment by Rockdow** [comment]
> When I was training, I found that most of the pictures were not properly extracted, some could and some could not, and most of them could not be extracted correctly ![image](https://user-images.githubusercontent.com/81903513/193197445-00122af4-f74f-4941-a20a-1436390fd11a.png) ![image](https://user-images.githubusercontent.com/81903513/193197745-a8332abc-b9ab-4b16-ad66-dbe0458b83da.png) Can you help me?

Hello, I am facing the same problem, if you have solved this problem, please teach me. Thanks for your valuable time!
