### ISSUE TITLE
Edges Extraction

### ISSUE THREAD

**Issue by 5agado** [geyuying/PF-AFN#8]
Could you share your code/setup for edge/mask extraction?

I simply obtained similar results using opencv canny edge detection and contours filling, but wanted to be sure to match your setup as closely as possible for reproducibility and quality comparison.

**Comment by geyuying** [comment]
The extracted edge for test on VITON are released in https://drive.google.com/file/d/1Y7uV0gomwWyxCvvH8TIbY7D9cTAUy6om/view (test_edge).

**Comment by 5agado** [comment]
Thanks for the quick reply! 
I was actually interested in extracting edges for new images.
I suppose then you just used the VITON data, and didn't extract any additional edges.

I'll look into their repo then, thanks

**Comment by wtSerious** [comment]
> Thanks for the quick reply! I was actually interested in extracting edges for new images. I suppose then you just used the VITON data, and didn't extract any additional edges.
> 
> I'll look into their repo then, thanks

Hello, I have the same problem as you. Have you found a solution to extract the edges?
